/*
 * Reactive Web Firewall - Apache module
 *
 * Copyright (C) 2026 Daniele Stefano Continenza <daniele@dascos.info>
 * SPDX-License-Identifier: AGPL-3.0-or-later
 *
 * Current development stage:
 *
 *   - Apache HTTP Server 2.4.x
 *   - early request inspection through post_read_request
 *   - external declarative rules
 *   - exact, prefix, path-regex and request-target-regex matching
 *   - custom minimal HTTP 403 response
 *   - no nftables yet
 *   - no SSH yet
 *   - asynchronous local helper notification over Unix datagram socket
 *   - no nftables/SSH/firewall work inside Apache
 *   - shared short-lived IP cache across Apache workers
 *   - IPv4/IPv6 trusted-client whitelist
 *   - optional connection close/abort after rule/cache blocks
 *   - optional access-log suppression for cached follow-up requests
 *   - DEBUG microsecond timing for RwF and full Apache transaction
 *
 * The module inspects the original client request immediately after
 * Apache has read and parsed it.
 *
 * If a rule matches, normal request processing is stopped with a
 * custom HTTP 403 response generated by RwF itself.
 *
 * Requests which do not match any active rule return DECLINED and
 * continue through Apache normally.
 */

#include <ctype.h>
#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
#include <string.h>
#include <strings.h>
#include <unistd.h>
#include <sys/socket.h>
#include <sys/un.h>

#include "httpd.h"
#include "http_config.h"
#include "http_connection.h"
#include "http_log.h"
#include "http_protocol.h"
#include "http_request.h"
#include "http_core.h"

#include "ap_mpm.h"
#include "ap_regex.h"

#include "apr_global_mutex.h"
#include "apr_network_io.h"
#include "apr_shm.h"
#include "apr_strings.h"
#include "apr_tables.h"
#include "apr_time.h"


APLOG_USE_MODULE(rwf);


/*
 * Default RwF response.
 *
 * This response is deliberately generated by the module itself so that
 * a blocked request never reaches the site's ErrorDocument, rewrite
 * rules, PHP application, CMS, reverse proxy handler, etc.
 */
#define RWF_BLOCK_RESPONSE \
"\"<!doctype html>" \
"<html lang=\"en\">" \
"<head>" \
"<meta charset=\"utf-8\">" \
"<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">" \
"<title>403 - Request blocked by RwF</title>" \
"<style>" \
"body{" \
"font-family:system-ui,-apple-system,BlinkMacSystemFont,\"Segoe UI\",sans-serif;" \
"background:#f5f5f5;" \
"color:#222;" \
"margin:0;" \
"padding:0;" \
"}" \
"main{" \
"max-width:700px;" \
"margin:10vh auto;" \
"padding:2rem;" \
"background:#fff;" \
"border:1px solid #ddd;" \
"border-radius:8px;" \
"}" \
"h1{margin-top:0;font-size:1.8rem;}" \
"p{line-height:1.5;}" \
"small{color:#666;}" \
"</style>" \
"</head>" \
"<body>" \
"<main>" \
"<h1>403 - Request blocked</h1>" \
"<p>" \
"Reactive Web Firewall (RwF) blocked this request because it matched " \
"an active security rule." \
"</p>" \
"<p>" \
"If you believe this is an error, contact the site administrator." \
"</p>" \
"<small>Protected by Reactive Web Firewall</small>" \
"</main>" \
"</body>" \
"</html>"


/*
 * Empty literal response used for cache hits.
 *
 * ap_custom_response() expects a literal body to start with a double
 * quote. A string containing only that marker therefore produces an
 * empty HTTP 403 body and prevents Apache from invoking ErrorDocument.
 */
#define RWF_CACHE_BLOCK_RESPONSE "\""


/*
 * Shared cache parameters.
 *
 * 2048 buckets x 4 ways = 8192 simultaneously remembered IPs.
 * Each lookup examines at most four entries.
 *
 * The TTL is deliberately short. The cache is only the immediate shield
 * between the first high-confidence match and the future real firewall ban.
 */
#define RWF_CACHE_BUCKETS     2048
#define RWF_CACHE_WAYS        4
#define RWF_CACHE_IP_LEN      64
#define RWF_CACHE_TTL_SECONDS 300


/*
 * Supported rule types.
 */
typedef enum {
    RWF_MATCH_EXACT = 1,
    RWF_MATCH_PREFIX,
    RWF_MATCH_REGEX,
    RWF_MATCH_TARGET_REGEX
} rwf_match_type;


/*
 * One configured RwF rule.
 *
 * name:
 *   Human-readable/internal rule identifier.
 *
 * type:
 *   Exact, Prefix, path Regex or request-target Regex.
 *
 * pattern:
 *   Path or regular expression.
 *
 * policy:
 *   Firewall policy forwarded to the privileged helper when configured.
 *   Examples:
 *
 *     permanent
 *     1h
 *     3d
 *     2w
 *     3600
 *     off
 *
 * regex:
 *   Compiled representation, used by Regex and TargetRegex rules.
 */
typedef struct {
    const char *name;
    rwf_match_type type;
    const char *pattern;
    const char *policy;
    ap_regex_t *regex;
} rwf_rule;


/*
 * One trusted client/network entry.
 *
 * subnet:
 *   APR pre-parsed IPv4/IPv6 network.
 *
 * spec:
 *   Original administrator-facing value, used only for debug logging.
 */
typedef struct {
    apr_ipsubnet_t *subnet;
    const char *spec;
} rwf_whitelist_entry;


/*
 * Per-server / per-vhost configuration.
 *
 * enabled:
 *
 *   -1 = not explicitly configured
 *    0 = disabled
 *    1 = enabled
 */
typedef struct {
    int enabled;
    int drop_connection;
    int suppress_blocked_accesslog;
    const char *helper_socket;
    apr_array_header_t *whitelist;
    apr_array_header_t *rules;
} rwf_server_conf;


/*
 * Per-request timing context.
 *
 * rwf_enter_us / rwf_exit_us delimit only the time spent inside RwF's
 * post_read_request hook.
 *
 * Apache's own r->request_time and the later log_transaction hook let us
 * also observe the time before RwF and the remainder of the Apache request.
 */
typedef struct {
    apr_time_t rwf_enter_us;
    apr_time_t rwf_exit_us;
    const char *outcome;
} rwf_request_ctx;


/*
 * One entry in the shared fast-block cache.
 */
typedef struct {
    char ip[RWF_CACHE_IP_LEN];
    apr_time_t expires_at;
    apr_uint32_t hit_count;
} rwf_cache_entry;


/*
 * Set-associative cache.
 *
 * Hashing selects one bucket and only the four entries in that bucket
 * are inspected. This avoids a full scan while keeping collision handling
 * simple and deterministic.
 */
typedef struct {
    rwf_cache_entry buckets[RWF_CACHE_BUCKETS][RWF_CACHE_WAYS];
} rwf_cache_state;


/*
 * Runtime cache handles.
 *
 * The shared-memory mapping is inherited by Apache children on Unix.
 * The global mutex protects both processes and threads.
 */
static apr_shm_t *rwf_cache_shm = NULL;
static rwf_cache_state *rwf_cache = NULL;
static apr_global_mutex_t *rwf_cache_mutex = NULL;
static const char *rwf_cache_mutex_file = NULL;
static int rwf_cache_ready = 0;


/*
 * Release a regex compiled through ap_regcomp().
 */
static apr_status_t rwf_regex_cleanup(void *data)
{
    ap_regex_t *regex = (ap_regex_t *) data;

    if (regex != NULL) {
        ap_regfree(regex);
    }

    return APR_SUCCESS;
}


/*
 * Convert rule type to a printable string.
 */
static const char *rwf_rule_type_name(rwf_match_type type)
{
    switch (type) {
        case RWF_MATCH_EXACT:
            return "exact";

        case RWF_MATCH_PREFIX:
            return "prefix";

        case RWF_MATCH_REGEX:
            return "regex";

        case RWF_MATCH_TARGET_REGEX:
            return "target-regex";

        default:
            return "unknown";
    }
}


/*
 * Validate a rule identifier.
 *
 * Allowed characters:
 *
 *   A-Z
 *   a-z
 *   0-9
 *   _
 *   -
 *   .
 */
static int rwf_valid_rule_name(const char *name)
{
    const unsigned char *p;

    if (name == NULL || *name == '\0') {
        return 0;
    }

    p = (const unsigned char *) name;

    while (*p != '\0') {

        if (!isalnum(*p) &&
            *p != '_' &&
            *p != '-' &&
            *p != '.') {

            return 0;
        }

        ++p;
    }

    return 1;
}


/*
 * Validate policy syntax.
 *
 * Accepted:
 *
 *   off
 *   permanent
 *   3600
 *   30s
 *   30m
 *   4h
 *   3d
 *   2w
 *
 * The policy is forwarded unchanged to the privileged helper, which
 * translates it into the configured firewall action.
 */
static int rwf_valid_policy(const char *policy)
{
    apr_size_t len;
    apr_size_t i;
    apr_size_t digits;

    if (policy == NULL || *policy == '\0') {
        return 0;
    }

    if (strcasecmp(policy, "off") == 0 ||
        strcasecmp(policy, "permanent") == 0) {

        return 1;
    }

    len = strlen(policy);

    if (len == 0) {
        return 0;
    }

    digits = len;

    switch (policy[len - 1]) {
        case 's':
        case 'S':
        case 'm':
        case 'M':
        case 'h':
        case 'H':
        case 'd':
        case 'D':
        case 'w':
        case 'W':
            digits = len - 1;
            break;

        default:
            break;
    }

    if (digits == 0) {
        return 0;
    }

    for (i = 0; i < digits; ++i) {

        if (!isdigit((unsigned char) policy[i])) {
            return 0;
        }
    }

    /*
     * If there was no suffix, all characters must have been digits.
     */
    if (digits == len) {
        return 1;
    }

    /*
     * With suffix, it must be exactly the final character.
     */
    return digits == (len - 1);
}


/*
 * Create configuration for the main server or a VirtualHost.
 */
static void *rwf_create_server_conf(apr_pool_t *pool, server_rec *server)
{
    rwf_server_conf *conf;

    (void) server;

    conf = apr_pcalloc(pool, sizeof(*conf));

    conf->enabled = -1;
    conf->drop_connection = -1;
    conf->suppress_blocked_accesslog = -1;
    conf->helper_socket = NULL;

    conf->whitelist = apr_array_make(
        pool,
        8,
        sizeof(rwf_whitelist_entry)
    );

    conf->rules = apr_array_make(
        pool,
        16,
        sizeof(rwf_rule)
    );

    return conf;
}


/*
 * Merge parent and VirtualHost configuration.
 *
 * Global rules are inherited by VirtualHosts.
 * Rules declared inside a VirtualHost are appended.
 */
static void *rwf_merge_server_conf(apr_pool_t *pool,
                                   void *basev,
                                   void *addv)
{
    rwf_server_conf *base = (rwf_server_conf *) basev;
    rwf_server_conf *add  = (rwf_server_conf *) addv;
    rwf_server_conf *conf;

    conf = apr_pcalloc(pool, sizeof(*conf));

    conf->enabled =
        (add->enabled != -1)
        ? add->enabled
        : base->enabled;

    conf->drop_connection =
        (add->drop_connection != -1)
        ? add->drop_connection
        : base->drop_connection;

    conf->suppress_blocked_accesslog =
        (add->suppress_blocked_accesslog != -1)
        ? add->suppress_blocked_accesslog
        : base->suppress_blocked_accesslog;

    conf->helper_socket =
        (add->helper_socket != NULL)
        ? add->helper_socket
        : base->helper_socket;

    conf->whitelist = apr_array_make(
        pool,
        (base->whitelist != NULL ? base->whitelist->nelts : 0) +
        (add->whitelist  != NULL ? add->whitelist->nelts  : 0) +
        2,
        sizeof(rwf_whitelist_entry)
    );

    if (base->whitelist != NULL) {
        apr_array_cat(conf->whitelist, base->whitelist);
    }

    if (add->whitelist != NULL) {
        apr_array_cat(conf->whitelist, add->whitelist);
    }

    conf->rules = apr_array_make(
        pool,
        (base->rules != NULL ? base->rules->nelts : 0) +
        (add->rules  != NULL ? add->rules->nelts  : 0) +
        4,
        sizeof(rwf_rule)
    );

    if (base->rules != NULL) {
        apr_array_cat(conf->rules, base->rules);
    }

    if (add->rules != NULL) {
        apr_array_cat(conf->rules, add->rules);
    }

    return conf;
}


/*
 * RwfEnabled On|Off
 */
static const char *rwf_set_enabled(cmd_parms *cmd,
                                   void *dummy,
                                   int flag)
{
    rwf_server_conf *conf;

    (void) dummy;

    conf = ap_get_module_config(
        cmd->server->module_config,
        &rwf_module
    );

    conf->enabled = flag ? 1 : 0;

    return NULL;
}


/*
 * RwfDropConnection On|Off
 *
 * When enabled, a rule match schedules the client connection for closure.
 * A subsequent cache hit escalates this to an abort of the request connection
 * and, for multiplexed protocols such as HTTP/2, its master connection.
 */
static const char *rwf_set_drop_connection(cmd_parms *cmd,
                                            void *dummy,
                                            int flag)
{
    rwf_server_conf *conf;

    (void) dummy;

    conf = ap_get_module_config(
        cmd->server->module_config,
        &rwf_module
    );

    conf->drop_connection = flag ? 1 : 0;

    return NULL;
}


/*
 * RwfSuppressBlockedAccessLog On|Off
 *
 * When enabled, cache-hit requests receive the environment variable
 * RWF_SUPPRESS_ACCESSLOG=1. CustomLog directives configured with
 * env=!RWF_SUPPRESS_ACCESSLOG therefore omit only already-cached follow-up
 * requests. The first request that matched a security rule remains logged.
 */
static const char *rwf_set_suppress_blocked_accesslog(cmd_parms *cmd,
                                                       void *dummy,
                                                       int flag)
{
    rwf_server_conf *conf;

    (void) dummy;

    conf = ap_get_module_config(
        cmd->server->module_config,
        &rwf_module
    );

    conf->suppress_blocked_accesslog = flag ? 1 : 0;

    return NULL;
}


/*
 * RwfHelperSocket /absolute/path/to/helper.sock
 *
 * Optional. If unset, RwF behaves exactly as before and no helper event
 * is emitted. The path must fit in sockaddr_un.sun_path.
 */
static const char *rwf_set_helper_socket(cmd_parms *cmd,
                                         void *dummy,
                                         const char *path)
{
    rwf_server_conf *conf;
    struct sockaddr_un addr;

    (void) dummy;

    if (path == NULL || *path == '\0') {
        return "RwF: RwfHelperSocket requires a non-empty absolute path";
    }

    if (path[0] != '/') {
        return apr_psprintf(
            cmd->pool,
            "RwF: RwfHelperSocket path must be absolute: '%s'",
            path
        );
    }

    if (strlen(path) >= sizeof(addr.sun_path)) {
        return apr_psprintf(
            cmd->pool,
            "RwF: RwfHelperSocket path is too long for AF_UNIX: '%s'",
            path
        );
    }

    conf = ap_get_module_config(
        cmd->server->module_config,
        &rwf_module
    );

    conf->helper_socket = apr_pstrdup(cmd->pool, path);

    return NULL;
}


/*
 * RwfWhitelistIP <ip-or-cidr>
 *
 * Examples:
 *
 *   RwfWhitelistIP 192.0.2.10
 *   RwfWhitelistIP 192.0.2.10/32
 *   RwfWhitelistIP 192.0.2.0/24
 *   RwfWhitelistIP 2001:db8::1/128
 *   RwfWhitelistIP 2001:db8::/32
 *
 * A bare address is treated as one exact host (/32 for IPv4, /128 for IPv6).
 * Whitelisted clients bypass both the fast cache and the rule engine and
 * never generate helper events.
 */
static const char *rwf_add_whitelist_ip(cmd_parms *cmd,
                                        void *dummy,
                                        const char *spec)
{
    rwf_server_conf *conf;
    rwf_whitelist_entry *entry;
    apr_ipsubnet_t *subnet;
    apr_status_t rv;

    char *work;
    char *slash;
    const char *mask;

    (void) dummy;

    if (spec == NULL || *spec == '\0') {
        return "RwF: RwfWhitelistIP requires an IP address or CIDR";
    }

    work = apr_pstrdup(cmd->pool, spec);
    slash = strrchr(work, '/');

    if (slash != NULL) {
        *slash = '\0';
        mask = slash + 1;

        if (*work == '\0' || *mask == '\0') {
            return apr_psprintf(
                cmd->pool,
                "RwF: invalid RwfWhitelistIP value '%s'",
                spec
            );
        }
    }
    else {
        /*
         * No mask means an exact host. A colon unambiguously identifies
         * an IPv6 literal for the configuration forms supported here.
         */
        mask = (strchr(work, ':') != NULL) ? "128" : "32";
    }

    subnet = NULL;

    rv = apr_ipsubnet_create(
        &subnet,
        work,
        mask,
        cmd->pool
    );

    if (rv != APR_SUCCESS || subnet == NULL) {
        return apr_psprintf(
            cmd->pool,
            "RwF: invalid RwfWhitelistIP value '%s'",
            spec
        );
    }

    conf = ap_get_module_config(
        cmd->server->module_config,
        &rwf_module
    );

    if (conf == NULL || conf->whitelist == NULL) {
        return "RwF: internal configuration error while adding whitelist entry";
    }

    entry = apr_array_push(conf->whitelist);
    entry->subnet = subnet;
    entry->spec = apr_pstrdup(cmd->pool, spec);

    return NULL;
}


/*
 * Common implementation for adding a rule.
 */
static const char *rwf_add_rule(cmd_parms *cmd,
                                rwf_match_type type,
                                const char *name,
                                const char *pattern,
                                const char *policy)
{
    rwf_server_conf *conf;
    rwf_rule *rule;

    if (!rwf_valid_rule_name(name)) {

        return apr_psprintf(
            cmd->pool,
            "RwF: invalid rule name '%s'. "
            "Allowed characters are letters, numbers, _, - and .",
            name != NULL ? name : ""
        );
    }

    if (pattern == NULL || *pattern == '\0') {

        return apr_psprintf(
            cmd->pool,
            "RwF rule '%s': empty pattern is not allowed",
            name
        );
    }

    if (!rwf_valid_policy(policy)) {

        return apr_psprintf(
            cmd->pool,
            "RwF rule '%s': invalid policy '%s'",
            name,
            policy != NULL ? policy : ""
        );
    }

    /*
     * Exact and prefix rules operate on URI paths.
     * Require a leading slash to avoid accidental malformed rules.
     */
    if ((type == RWF_MATCH_EXACT ||
         type == RWF_MATCH_PREFIX) &&
        pattern[0] != '/') {

        return apr_psprintf(
            cmd->pool,
            "RwF rule '%s': exact/prefix patterns must start with '/'",
            name
        );
    }

    conf = ap_get_module_config(
        cmd->server->module_config,
        &rwf_module
    );

    if (conf == NULL || conf->rules == NULL) {
        return "RwF: internal configuration error while adding rule";
    }

    rule = apr_array_push(conf->rules);

    memset(rule, 0, sizeof(*rule));

    rule->name = apr_pstrdup(cmd->pool, name);
    rule->type = type;
    rule->pattern = apr_pstrdup(cmd->pool, pattern);
    rule->policy = apr_pstrdup(cmd->pool, policy);
    rule->regex = NULL;

    /*
     * Compile regular expressions immediately while Apache is parsing
     * its configuration.
     *
     * A bad expression therefore causes apache2ctl configtest to fail
     * instead of becoming a runtime surprise.
     */
    if (type == RWF_MATCH_REGEX ||
        type == RWF_MATCH_TARGET_REGEX) {

        int rc;
        char error_buffer[256];

        rule->regex = apr_pcalloc(
            cmd->pool,
            sizeof(ap_regex_t)
        );

        rc = ap_regcomp(
            rule->regex,
            rule->pattern,
            AP_REG_ICASE
        );

        if (rc != 0) {

            ap_regerror(
                rc,
                rule->regex,
                error_buffer,
                sizeof(error_buffer)
            );

            /*
             * Remove the partially-created array element.
             */
            conf->rules->nelts--;

            return apr_psprintf(
                cmd->pool,
                "RwF rule '%s': invalid regular expression '%s': %s",
                name,
                pattern,
                error_buffer
            );
        }

        apr_pool_cleanup_register(
            cmd->pool,
            rule->regex,
            rwf_regex_cleanup,
            apr_pool_cleanup_null
        );
    }

    return NULL;
}


/*
 * RwfRuleExact <name> <path> <policy>
 */
static const char *rwf_add_exact_rule(cmd_parms *cmd,
                                      void *dummy,
                                      const char *name,
                                      const char *pattern,
                                      const char *policy)
{
    (void) dummy;

    return rwf_add_rule(
        cmd,
        RWF_MATCH_EXACT,
        name,
        pattern,
        policy
    );
}


/*
 * RwfRulePrefix <name> <path-prefix> <policy>
 */
static const char *rwf_add_prefix_rule(cmd_parms *cmd,
                                       void *dummy,
                                       const char *name,
                                       const char *pattern,
                                       const char *policy)
{
    (void) dummy;

    return rwf_add_rule(
        cmd,
        RWF_MATCH_PREFIX,
        name,
        pattern,
        policy
    );
}


/*
 * RwfRuleRegex <name> <regex> <policy>
 */
static const char *rwf_add_regex_rule(cmd_parms *cmd,
                                      void *dummy,
                                      const char *name,
                                      const char *pattern,
                                      const char *policy)
{
    (void) dummy;

    return rwf_add_rule(
        cmd,
        RWF_MATCH_REGEX,
        name,
        pattern,
        policy
    );
}


/*
 * RwfRuleTargetRegex <name> <regex> <policy>
 *
 * Unlike RwfRuleRegex, this rule sees a normalized request target:
 * path plus query string. Percent-encoded printable ASCII is decoded
 * for two passes, so evasions such as %2F and %252F are visible to
 * detection without changing Apache's own r->uri/r->args fields.
 */
static const char *rwf_add_target_regex_rule(cmd_parms *cmd,
                                             void *dummy,
                                             const char *name,
                                             const char *pattern,
                                             const char *policy)
{
    (void) dummy;

    return rwf_add_rule(
        cmd,
        RWF_MATCH_TARGET_REGEX,
        name,
        pattern,
        policy
    );
}


/*
 * Apache directives exposed by mod_rwf.
 *
 * They are server/vhost configuration directives and are intentionally
 * not available through .htaccess.
 */
static const command_rec rwf_directives[] = {

    AP_INIT_FLAG(
        "RwfEnabled",
        rwf_set_enabled,
        NULL,
        RSRC_CONF,
        "Enable or disable Reactive Web Firewall"
    ),

    AP_INIT_FLAG(
        "RwfDropConnection",
        rwf_set_drop_connection,
        NULL,
        RSRC_CONF,
        "Close/abort the client connection after RwF blocks a request"
    ),

    AP_INIT_FLAG(
        "RwfSuppressBlockedAccessLog",
        rwf_set_suppress_blocked_accesslog,
        NULL,
        RSRC_CONF,
        "Set RWF_SUPPRESS_ACCESSLOG on cached follow-up requests"
    ),

    AP_INIT_TAKE1(
        "RwfHelperSocket",
        rwf_set_helper_socket,
        NULL,
        RSRC_CONF,
        "Absolute path to the local RwF Unix datagram helper socket"
    ),

    AP_INIT_TAKE1(
        "RwfWhitelistIP",
        rwf_add_whitelist_ip,
        NULL,
        RSRC_CONF,
        "Trusted client IP or CIDR which bypasses RwF"
    ),

    AP_INIT_TAKE3(
        "RwfRuleExact",
        rwf_add_exact_rule,
        NULL,
        RSRC_CONF,
        "RwfRuleExact <name> <path> <policy>"
    ),

    AP_INIT_TAKE3(
        "RwfRulePrefix",
        rwf_add_prefix_rule,
        NULL,
        RSRC_CONF,
        "RwfRulePrefix <name> <path-prefix> <policy>"
    ),

    AP_INIT_TAKE3(
        "RwfRuleRegex",
        rwf_add_regex_rule,
        NULL,
        RSRC_CONF,
        "RwfRuleRegex <name> <path-regular-expression> <policy>"
    ),

    AP_INIT_TAKE3(
        "RwfRuleTargetRegex",
        rwf_add_target_regex_rule,
        NULL,
        RSRC_CONF,
        "RwfRuleTargetRegex <name> <request-target-regular-expression> <policy>"
    ),

    { NULL }
};


/*
 * Test one configured rule against the request path.
 *
 * Return:
 *
 *   1 = match
 *   0 = no match
 */
static int rwf_rule_matches(const rwf_rule *rule,
                            const char *path,
                            const char *target)
{
    apr_size_t prefix_len;
    const char *subject;

    if (rule == NULL ||
        path == NULL ||
        rule->pattern == NULL) {

        return 0;
    }

    /*
     * Disabled rules remain loaded but never match.
     */
    if (rule->policy != NULL &&
        strcasecmp(rule->policy, "off") == 0) {

        return 0;
    }

    switch (rule->type) {

        case RWF_MATCH_EXACT:

            /*
             * Deliberately case-insensitive.
             *
             * Scanner probes frequently vary case even when the actual
             * Linux filesystem is case-sensitive.
             */
            return strcasecmp(
                path,
                rule->pattern
            ) == 0;


        case RWF_MATCH_PREFIX:

            prefix_len = strlen(rule->pattern);

            if (strlen(path) < prefix_len) {
                return 0;
            }

            return strncasecmp(
                path,
                rule->pattern,
                prefix_len
            ) == 0;


        case RWF_MATCH_REGEX:
        case RWF_MATCH_TARGET_REGEX:

            if (rule->regex == NULL) {
                return 0;
            }

            subject =
                (rule->type == RWF_MATCH_TARGET_REGEX)
                ? (target != NULL ? target : path)
                : path;

            return ap_regexec(
                rule->regex,
                subject,
                0,
                NULL,
                0
            ) == 0;


        default:
            return 0;
    }
}


/*
 * Decode one percent-encoding pass for printable ASCII only.
 * Controls/NUL are deliberately left encoded. This is detection-only data:
 * Apache's own URI fields are never modified.
 */
static int rwf_hex_value(unsigned char c)
{
    if (c >= '0' && c <= '9') return c - '0';
    if (c >= 'a' && c <= 'f') return c - 'a' + 10;
    if (c >= 'A' && c <= 'F') return c - 'A' + 10;
    return -1;
}


static const char *rwf_percent_decode_printable(apr_pool_t *pool,
                                                 const char *input)
{
    apr_size_t i;
    apr_size_t o;
    apr_size_t len;
    char *out;

    if (input == NULL) {
        return "";
    }

    len = strlen(input);
    out = apr_palloc(pool, len + 1);
    o = 0;

    for (i = 0; i < len; ++i) {
        if (input[i] == '%' && i + 2 < len) {
            int hi = rwf_hex_value((unsigned char) input[i + 1]);
            int lo = rwf_hex_value((unsigned char) input[i + 2]);

            if (hi >= 0 && lo >= 0) {
                unsigned char decoded = (unsigned char) ((hi << 4) | lo);

                if (decoded >= 0x20 && decoded <= 0x7e) {
                    out[o++] = (char) decoded;
                    i += 2;
                    continue;
                }
            }
        }

        out[o++] = input[i];
    }

    out[o] = '\0';
    return out;
}


static const char *rwf_normalized_target(request_rec *r,
                                         const char *path)
{
    const char *raw;
    const char *pass1;

    if (r == NULL) {
        return path != NULL ? path : "";
    }

    raw = (r->args != NULL && *r->args != '\0')
        ? apr_pstrcat(r->pool, path != NULL ? path : "", "?", r->args, NULL)
        : (path != NULL ? path : "");

    pass1 = rwf_percent_decode_printable(r->pool, raw);
    return rwf_percent_decode_printable(r->pool, pass1);
}


/*
 * Return the effective user-agent IP for this request.
 *
 * request_rec->useragent_ip is the correct Apache 2.4 field when
 * mod_remoteip or a trusted proxy/load-balancer setup is in use.
 * Fall back to the directly connected peer for defensive compatibility.
 */
static const char *rwf_client_ip(request_rec *r)
{
    if (r == NULL) {
        return NULL;
    }

    if (r->useragent_ip != NULL && *r->useragent_ip != '\0') {
        return r->useragent_ip;
    }

    if (r->connection != NULL &&
        r->connection->client_ip != NULL &&
        *r->connection->client_ip != '\0') {

        return r->connection->client_ip;
    }

    return NULL;
}


/*
 * Return the whitelist entry matching this request, or NULL.
 *
 * Prefer request_rec->useragent_addr because mod_remoteip updates the
 * user-agent address seen by request-level modules. If it is unavailable,
 * rebuild a numeric sockaddr from the textual client IP.
 */
static const rwf_whitelist_entry *rwf_whitelist_match(
    request_rec *r,
    const rwf_server_conf *conf,
    const char *client_ip)
{
    apr_sockaddr_t *addr;
    const rwf_whitelist_entry *entries;
    int i;

    if (r == NULL ||
        conf == NULL ||
        conf->whitelist == NULL ||
        conf->whitelist->nelts == 0 ||
        client_ip == NULL ||
        *client_ip == '\0') {

        return NULL;
    }

    addr = r->useragent_addr;

    if (addr == NULL) {
        if (apr_sockaddr_info_get(
                &addr,
                client_ip,
                APR_UNSPEC,
                0,
                0,
                r->pool
            ) != APR_SUCCESS) {

            return NULL;
        }
    }

    entries = (const rwf_whitelist_entry *) conf->whitelist->elts;

    for (i = 0; i < conf->whitelist->nelts; ++i) {
        if (entries[i].subnet != NULL &&
            apr_ipsubnet_test(entries[i].subnet, addr)) {

            return &entries[i];
        }
    }

    return NULL;
}


/*
 * Mark a cache-hit request so mod_log_config can omit it when its CustomLog
 * directive uses: env=!RWF_SUPPRESS_ACCESSLOG
 */
static void rwf_suppress_accesslog(request_rec *r,
                                   const rwf_server_conf *conf)
{
    if (r == NULL || conf == NULL ||
        conf->suppress_blocked_accesslog != 1 ||
        r->subprocess_env == NULL) {
        return;
    }

    apr_table_setn(
        r->subprocess_env,
        "RWF_SUPPRESS_ACCESSLOG",
        "1"
    );
}


/*
 * Close or abort the connection without depending on mod_http2 internals.
 *
 * On the first rule match we request AP_CONN_CLOSE so the explanatory 403 can
 * still complete normally. If another request from the same IP reaches RwF
 * through the shared cache, it is already a follow-up/parallel request and we
 * additionally mark both the request connection and its master as aborted.
 * For HTTP/2 this targets the physical master session rather than only one
 * logical stream.
 */
static void rwf_drop_client_connection(request_rec *r, int aggressive)
{
    conn_rec *c;
    conn_rec *master;

    if (r == NULL || r->connection == NULL) {
        return;
    }

    c = r->connection;
    master = (c->master != NULL) ? c->master : c;

    c->keepalive = AP_CONN_CLOSE;
    if (master != c) {
        master->keepalive = AP_CONN_CLOSE;
    }

    if (aggressive) {
        c->aborted = 1;
        if (master != c) {
            master->aborted = 1;
        }
    }
}


/*
 * Attach a timing context to the original request.
 */
static rwf_request_ctx *rwf_timing_begin(request_rec *r,
                                         apr_time_t rwf_enter_us)
{
    rwf_request_ctx *ctx;

    if (r == NULL || r->request_config == NULL) {
        return NULL;
    }

    ctx = apr_pcalloc(r->pool, sizeof(*ctx));
    ctx->rwf_enter_us = rwf_enter_us;
    ctx->rwf_exit_us = 0;
    ctx->outcome = "unknown";

    ap_set_module_config(
        r->request_config,
        &rwf_module,
        ctx
    );

    return ctx;
}


/*
 * Mark the end of RwF processing and optionally emit the detailed timing
 * record. The timestamp is captured BEFORE the debug log call so logging
 * overhead is not included in rwf_duration_us.
 */
static void rwf_timing_finish(request_rec *r,
                              rwf_request_ctx *ctx,
                              const char *client_ip,
                              const char *outcome)
{
    apr_interval_time_t apache_to_rwf_us;
    apr_interval_time_t rwf_duration_us;

    if (r == NULL || ctx == NULL) {
        return;
    }

    ctx->rwf_exit_us = apr_time_now();
    ctx->outcome = (outcome != NULL) ? outcome : "unknown";

    if (!APLOGrdebug(r)) {
        return;
    }

    apache_to_rwf_us =
        (r->request_time > 0 && ctx->rwf_enter_us >= r->request_time)
        ? (ctx->rwf_enter_us - r->request_time)
        : 0;

    rwf_duration_us =
        (ctx->rwf_exit_us >= ctx->rwf_enter_us)
        ? (ctx->rwf_exit_us - ctx->rwf_enter_us)
        : 0;

    ap_log_rerror(
        APLOG_MARK,
        APLOG_DEBUG,
        0,
        r,
        "mod_rwf: timing-rwf "
        "client=%s "
        "outcome=%s "
        "apache_start_us=%" APR_TIME_T_FMT " "
        "rwf_enter_us=%" APR_TIME_T_FMT " "
        "rwf_exit_us=%" APR_TIME_T_FMT " "
        "apache_to_rwf_us=%" APR_TIME_T_FMT " "
        "rwf_duration_us=%" APR_TIME_T_FMT,
        client_ip != NULL ? client_ip : "-",
        ctx->outcome,
        r->request_time,
        ctx->rwf_enter_us,
        ctx->rwf_exit_us,
        apache_to_rwf_us,
        rwf_duration_us
    );
}


/*
 * Final Apache transaction timing.
 *
 * This executes later than post_read_request and therefore measures the
 * remainder of Apache processing after RwF has returned its decision.
 * It is intentionally DEBUG-only.
 */
static int rwf_log_transaction(request_rec *r)
{
    rwf_request_ctx *ctx;
    apr_time_t apache_end_us;
    apr_interval_time_t apache_to_rwf_us;
    apr_interval_time_t rwf_duration_us;
    apr_interval_time_t post_rwf_us;
    apr_interval_time_t apache_total_us;

    if (r == NULL || r->request_config == NULL) {
        return DECLINED;
    }

    ctx = ap_get_module_config(
        r->request_config,
        &rwf_module
    );

    if (ctx == NULL || ctx->rwf_enter_us == 0 || ctx->rwf_exit_us == 0) {
        return DECLINED;
    }

    if (!APLOGrdebug(r)) {
        return DECLINED;
    }

    apache_end_us = apr_time_now();

    apache_to_rwf_us =
        (r->request_time > 0 && ctx->rwf_enter_us >= r->request_time)
        ? (ctx->rwf_enter_us - r->request_time)
        : 0;

    rwf_duration_us =
        (ctx->rwf_exit_us >= ctx->rwf_enter_us)
        ? (ctx->rwf_exit_us - ctx->rwf_enter_us)
        : 0;

    post_rwf_us =
        (apache_end_us >= ctx->rwf_exit_us)
        ? (apache_end_us - ctx->rwf_exit_us)
        : 0;

    apache_total_us =
        (r->request_time > 0 && apache_end_us >= r->request_time)
        ? (apache_end_us - r->request_time)
        : 0;

    ap_log_rerror(
        APLOG_MARK,
        APLOG_DEBUG,
        0,
        r,
        "mod_rwf: timing-transaction "
        "client=%s "
        "outcome=%s "
        "apache_start_us=%" APR_TIME_T_FMT " "
        "rwf_enter_us=%" APR_TIME_T_FMT " "
        "rwf_exit_us=%" APR_TIME_T_FMT " "
        "apache_end_us=%" APR_TIME_T_FMT " "
        "apache_to_rwf_us=%" APR_TIME_T_FMT " "
        "rwf_duration_us=%" APR_TIME_T_FMT " "
        "post_rwf_us=%" APR_TIME_T_FMT " "
        "apache_total_us=%" APR_TIME_T_FMT,
        rwf_client_ip(r) != NULL ? rwf_client_ip(r) : "-",
        ctx->outcome != NULL ? ctx->outcome : "unknown",
        r->request_time,
        ctx->rwf_enter_us,
        ctx->rwf_exit_us,
        apache_end_us,
        apache_to_rwf_us,
        rwf_duration_us,
        post_rwf_us,
        apache_total_us
    );

    return DECLINED;
}


/*
 * FNV-1a hash for the textual IP representation supplied by Apache.
 */
static apr_uint32_t rwf_cache_hash(const char *ip)
{
    const unsigned char *p;
    apr_uint32_t hash;

    hash = 2166136261u;
    p = (const unsigned char *) ip;

    while (p != NULL && *p != '\0') {
        hash ^= (apr_uint32_t) *p++;
        hash *= 16777619u;
    }

    return hash;
}


/*
 * Check whether an IP is currently present in the fast-block cache.
 *
 * Expired entries in the selected bucket are lazily cleared here.
 * On any cache/mutex problem we fail open and let the normal rule engine
 * continue, preserving the behavior of the previously tested module.
 */
static int rwf_cache_lookup(const char *ip,
                            apr_interval_time_t *remaining,
                            apr_uint32_t *hit_count)
{
    apr_status_t rv;
    apr_time_t now;
    apr_uint32_t bucket;
    int way;
    int found;

    if (!rwf_cache_ready ||
        rwf_cache == NULL ||
        rwf_cache_mutex == NULL ||
        ip == NULL ||
        *ip == '\0') {

        return 0;
    }

    /*
     * Never serialize normal web traffic behind the cache mutex.
     *
     * If another worker is touching the selected shared table right now,
     * fail open immediately and let the already-tested rule engine run.
     * Cache hits are an optimization / immediate shield, not a dependency
     * for request correctness.
     */
    rv = apr_global_mutex_trylock(rwf_cache_mutex);

    if (rv != APR_SUCCESS) {
        return 0;
    }

    now = apr_time_now();
    bucket = rwf_cache_hash(ip) % RWF_CACHE_BUCKETS;
    found = 0;

    for (way = 0; way < RWF_CACHE_WAYS; ++way) {
        rwf_cache_entry *entry;

        entry = &rwf_cache->buckets[bucket][way];

        if (entry->ip[0] == '\0') {
            continue;
        }

        if (entry->expires_at <= now) {
            entry->ip[0] = '\0';
            entry->expires_at = 0;
            entry->hit_count = 0;
            continue;
        }

        if (strcmp(entry->ip, ip) == 0) {
            found = 1;
            entry->hit_count++;

            if (remaining != NULL) {
                *remaining = entry->expires_at - now;
            }

            if (hit_count != NULL) {
                *hit_count = entry->hit_count;
            }

            break;
        }
    }

    apr_global_mutex_unlock(rwf_cache_mutex);

    return found;
}


/*
 * Add an IP to the fast-block cache.
 *
 * Existing live entries are deliberately NOT refreshed: a client cannot
 * keep itself cached forever merely by continuing to send requests.
 *
 * If all four ways in the selected bucket are occupied, replace the entry
 * that expires first.
 *
 * Return:
 *
 *   1 = inserted/replaced
 *   0 = already present or cache unavailable
 */
static int rwf_cache_add(const char *ip)
{
    apr_status_t rv;
    apr_time_t now;
    apr_time_t oldest_expiry;
    apr_uint32_t bucket;
    rwf_cache_entry *target;
    int way;

    if (!rwf_cache_ready ||
        rwf_cache == NULL ||
        rwf_cache_mutex == NULL ||
        ip == NULL ||
        *ip == '\0') {

        return 0;
    }

    rv = apr_global_mutex_lock(rwf_cache_mutex);

    if (rv != APR_SUCCESS) {
        return 0;
    }

    now = apr_time_now();
    bucket = rwf_cache_hash(ip) % RWF_CACHE_BUCKETS;
    target = NULL;
    oldest_expiry = 0;

    for (way = 0; way < RWF_CACHE_WAYS; ++way) {
        rwf_cache_entry *entry;

        entry = &rwf_cache->buckets[bucket][way];

        if (entry->ip[0] != '\0' &&
            entry->expires_at > now &&
            strcmp(entry->ip, ip) == 0) {

            apr_global_mutex_unlock(rwf_cache_mutex);
            return 0;
        }

        if (entry->ip[0] == '\0' || entry->expires_at <= now) {
            target = entry;
            break;
        }

        if (target == NULL || entry->expires_at < oldest_expiry) {
            target = entry;
            oldest_expiry = entry->expires_at;
        }
    }

    if (target != NULL) {
        apr_cpystrn(target->ip, ip, sizeof(target->ip));
        target->expires_at = now + apr_time_from_sec(RWF_CACHE_TTL_SECONDS);
        target->hit_count = 0;
    }

    apr_global_mutex_unlock(rwf_cache_mutex);

    return target != NULL;
}


/*
 * Apply headers and a module-owned HTTP 403 response.
 *
 * The response string is expected to use Apache's literal-response marker
 * (a leading double quote), preventing vhost ErrorDocument processing.
 */
/*
 * Copy one textual event field into a fixed buffer while removing
 * separators/control characters that could corrupt the line protocol.
 */
static void rwf_event_field_copy(char *dst,
                                 apr_size_t dst_size,
                                 const char *src)
{
    apr_size_t i;

    if (dst == NULL || dst_size == 0) {
        return;
    }

    if (src == NULL || *src == '\0') {
        apr_cpystrn(dst, "-", dst_size);
        return;
    }

    i = 0;

    while (*src != '\0' && i + 1 < dst_size) {
        unsigned char c = (unsigned char) *src++;

        if (c == '\t' || c == '\r' || c == '\n' || c < 0x20 || c == 0x7f) {
            dst[i++] = '_';
        }
        else {
            dst[i++] = (char) c;
        }
    }

    dst[i] = '\0';
}


/*
 * Emit one high-confidence match to the local helper.
 *
 * Transport: AF_UNIX / SOCK_DGRAM.
 * sendto() uses MSG_DONTWAIT, therefore Apache never waits for the helper.
 * No SSH, nftables, subprocess or firewall operation is performed here.
 *
 * Return:
 *   1 = datagram queued to the helper
 *   0 = helper disabled or send failed
 */
static int rwf_notify_helper(request_rec *r,
                             const rwf_server_conf *conf,
                             const char *client_ip,
                             const char *hostname,
                             const char *method,
                             const char *path,
                             const rwf_rule *rule)
{
    int fd;
    int saved_errno;
    ssize_t sent;
    struct sockaddr_un addr;

    char ip_field[64];
    char host_field[256];
    char method_field[32];
    char uri_field[1024];
    char rule_field[128];
    char policy_field[64];
    char event[1792];

    int event_len;

    if (conf == NULL ||
        conf->helper_socket == NULL ||
        *conf->helper_socket == '\0' ||
        rule == NULL) {

        return 0;
    }

    rwf_event_field_copy(ip_field, sizeof(ip_field), client_ip);
    rwf_event_field_copy(host_field, sizeof(host_field), hostname);
    rwf_event_field_copy(method_field, sizeof(method_field), method);
    rwf_event_field_copy(uri_field, sizeof(uri_field), path);
    rwf_event_field_copy(rule_field, sizeof(rule_field), rule->name);
    rwf_event_field_copy(policy_field, sizeof(policy_field), rule->policy);

    event_len = snprintf(
        event,
        sizeof(event),
        "v=1\tip=%s\thost=%s\tmethod=%s\turi=%s\trule=%s\tpolicy=%s\tts_us=%" APR_TIME_T_FMT,
        ip_field,
        host_field,
        method_field,
        uri_field,
        rule_field,
        policy_field,
        apr_time_now()
    );

    if (event_len < 0 || (apr_size_t) event_len >= sizeof(event)) {
        ap_log_rerror(
            APLOG_MARK,
            APLOG_WARNING,
            0,
            r,
            "mod_rwf: helper-send-failed client=%s rule=%s reason=event-too-large",
            ip_field,
            rule_field
        );

        return 0;
    }

    fd = socket(AF_UNIX, SOCK_DGRAM, 0);

    if (fd < 0) {
        saved_errno = errno;

        ap_log_rerror(
            APLOG_MARK,
            APLOG_WARNING,
            0,
            r,
            "mod_rwf: helper-send-failed client=%s rule=%s reason=socket errno=%d error=%s",
            ip_field,
            rule_field,
            saved_errno,
            strerror(saved_errno)
        );

        return 0;
    }

    (void) fcntl(fd, F_SETFD, FD_CLOEXEC);

    memset(&addr, 0, sizeof(addr));
    addr.sun_family = AF_UNIX;
    apr_cpystrn(addr.sun_path, conf->helper_socket, sizeof(addr.sun_path));

    sent = sendto(
        fd,
        event,
        (size_t) event_len,
        MSG_DONTWAIT,
        (const struct sockaddr *) &addr,
        sizeof(addr)
    );

    if (sent < 0) {
        saved_errno = errno;
        close(fd);

        ap_log_rerror(
            APLOG_MARK,
            APLOG_WARNING,
            0,
            r,
            "mod_rwf: helper-send-failed client=%s rule=%s socket=%s errno=%d error=%s",
            ip_field,
            rule_field,
            conf->helper_socket,
            saved_errno,
            strerror(saved_errno)
        );

        return 0;
    }

    close(fd);

    ap_log_rerror(
        APLOG_MARK,
        APLOG_NOTICE,
        0,
        r,
        "mod_rwf: helper-sent client=%s rule=%s policy=%s bytes=%ld socket=%s",
        ip_field,
        rule_field,
        policy_field,
        (long) sent,
        conf->helper_socket
    );

    return 1;
}


static void rwf_prepare_forbidden_response(request_rec *r,
                                           const char *response)
{
    apr_table_setn(
        r->err_headers_out,
        "X-RwF",
        "blocked"
    );

    apr_table_setn(
        r->err_headers_out,
        "Cache-Control",
        "no-store"
    );

    apr_table_setn(
        r->err_headers_out,
        "X-Content-Type-Options",
        "nosniff"
    );

    ap_custom_response(
        r,
        HTTP_FORBIDDEN,
        response
    );
}


/*
 * Initialize the process-shared fast-block cache after Apache has parsed
 * and validated its configuration.
 *
 * Apache invokes post_config during the initial preflight pass as well.
 * ap_state_query() lets us skip that first pass and create runtime state
 * only when the server is actually starting the worker generation.
 *
 * Cache setup is fail-open: if shared memory or locking cannot be created,
 * the previously tested rule engine remains fully operational.
 */
static int rwf_post_config(apr_pool_t *pconf,
                           apr_pool_t *plog,
                           apr_pool_t *ptemp,
                           server_rec *server)
{
    apr_status_t rv;

    (void) plog;
    (void) ptemp;

    if (ap_state_query(AP_SQ_MAIN_STATE) == AP_SQ_MS_CREATE_PRE_CONFIG) {
        return OK;
    }

    rwf_cache_ready = 0;
    rwf_cache_shm = NULL;
    rwf_cache = NULL;
    rwf_cache_mutex = NULL;
    rwf_cache_mutex_file = NULL;

    rv = apr_shm_create(
        &rwf_cache_shm,
        sizeof(rwf_cache_state),
        NULL,
        pconf
    );

    if (rv != APR_SUCCESS) {
        ap_log_error(
            APLOG_MARK,
            APLOG_ERR,
            rv,
            server,
            "mod_rwf: shared cache disabled: apr_shm_create failed"
        );

        return OK;
    }

    rwf_cache = (rwf_cache_state *) apr_shm_baseaddr_get(rwf_cache_shm);

    if (rwf_cache == NULL) {
        ap_log_error(
            APLOG_MARK,
            APLOG_ERR,
            0,
            server,
            "mod_rwf: shared cache disabled: shared-memory base address unavailable"
        );

        return OK;
    }

    memset(rwf_cache, 0, sizeof(*rwf_cache));

    rwf_cache_mutex_file = ap_runtime_dir_relative(
        pconf,
        "rwf-cache.lock"
    );

    if (rwf_cache_mutex_file == NULL) {
        ap_log_error(
            APLOG_MARK,
            APLOG_ERR,
            0,
            server,
            "mod_rwf: shared cache disabled: cannot resolve runtime mutex path"
        );

        return OK;
    }

    rv = apr_global_mutex_create(
        &rwf_cache_mutex,
        rwf_cache_mutex_file,
        APR_LOCK_DEFAULT,
        pconf
    );

    if (rv != APR_SUCCESS) {
        ap_log_error(
            APLOG_MARK,
            APLOG_ERR,
            rv,
            server,
            "mod_rwf: shared cache disabled: apr_global_mutex_create failed"
        );

        rwf_cache_mutex = NULL;
        return OK;
    }

    rwf_cache_ready = 1;

    ap_log_error(
        APLOG_MARK,
        APLOG_NOTICE,
        0,
        server,
        "mod_rwf: shared cache initialized "
        "slots=%d buckets=%d ways=%d ttl=%ds",
        RWF_CACHE_BUCKETS * RWF_CACHE_WAYS,
        RWF_CACHE_BUCKETS,
        RWF_CACHE_WAYS,
        RWF_CACHE_TTL_SECONDS
    );

    return OK;
}


/*
 * Re-open the global mutex in each Apache child for portability across
 * APR locking implementations.
 */
static void rwf_child_init(apr_pool_t *pchild,
                           server_rec *server)
{
    apr_status_t rv;

    if (!rwf_cache_ready || rwf_cache_mutex == NULL) {
        return;
    }

    rv = apr_global_mutex_child_init(
        &rwf_cache_mutex,
        rwf_cache_mutex_file,
        pchild
    );

    if (rv != APR_SUCCESS) {
        rwf_cache_ready = 0;

        ap_log_error(
            APLOG_MARK,
            APLOG_ERR,
            rv,
            server,
            "mod_rwf: shared cache disabled in child: mutex child_init failed"
        );
    }
}


/*
 * Early request inspection.
 *
 * post_read_request runs immediately after Apache has read and parsed
 * the client request.
 */
static int rwf_post_read_request(request_rec *r)
{
    rwf_server_conf *conf;
    rwf_request_ctx *timing_ctx;

    const rwf_whitelist_entry *whitelist_match;

    const char *path;
    const char *target;
    const char *client_ip;
    const char *hostname;
    const char *method;

    const rwf_rule *rules;
    const rwf_rule *matched_rule;

    apr_interval_time_t cache_remaining;
    apr_time_t rwf_enter_us;
    apr_uint32_t cache_hit_count;

    int cache_added;
    int i;

    /*
     * Capture this as the very first operation in the hook.
     *
     * It is the closest timestamp RwF can provide to "request entered RwF".
     * Apache's earlier r->request_time is logged separately.
     */
    rwf_enter_us = apr_time_now();

    conf = ap_get_module_config(
        r->server->module_config,
        &rwf_module
    );

    /*
     * Fail open.
     *
     * Missing or disabled configuration must never interfere with
     * normal Apache operation.
     */
    if (conf == NULL || conf->enabled != 1) {
        return DECLINED;
    }

    /*
     * Ignore subrequests and internal redirects.
     *
     * RwF evaluates and times only the original external client request.
     */
    if (r->main != NULL || r->prev != NULL) {
        return DECLINED;
    }

    timing_ctx = rwf_timing_begin(r, rwf_enter_us);

    /*
     * Resolve the effective client before cache/rules.
     */
    client_ip = rwf_client_ip(r);

    /*
     * Trusted clients bypass EVERYTHING in RwF:
     *
     *   - no cache lookup
     *   - no rule matching
     *   - no cache insertion
     *   - no helper event
     *   - no RwF-generated 403
     *
     * This check intentionally precedes the cache, so an address that was
     * cached before being whitelisted becomes immediately usable after an
     * Apache reload with the new configuration.
     */
    whitelist_match = rwf_whitelist_match(
        r,
        conf,
        client_ip
    );

    if (whitelist_match != NULL) {
        if (APLOGrdebug(r)) {
            ap_log_rerror(
                APLOG_MARK,
                APLOG_DEBUG,
                0,
                r,
                "mod_rwf: whitelist-hit "
                "client=%s "
                "entry=%s "
                "action=bypass",
                client_ip != NULL ? client_ip : "-",
                whitelist_match->spec != NULL ? whitelist_match->spec : "-"
            );
        }

        rwf_timing_finish(
            r,
            timing_ctx,
            client_ip,
            "whitelist-bypass"
        );

        return DECLINED;
    }

    cache_remaining = 0;
    cache_hit_count = 0;

    if (rwf_cache_lookup(client_ip, &cache_remaining, &cache_hit_count)) {

        path = (r->uri != NULL) ? r->uri : "";

        hostname =
            (r->hostname != NULL)
            ? r->hostname
            : "-";

        method =
            (r->method != NULL)
            ? r->method
            : "-";

        apr_table_setn(
            r->notes,
            "rwf.cache",
            "hit"
        );

        rwf_suppress_accesslog(r, conf);

        if (conf->drop_connection == 1) {
            rwf_drop_client_connection(r, 1);
        }

        /*
         * Empty module-owned 403 body.
         *
         * In particular: no ErrorDocument, no rewrite, no PHP/CMS,
         * and no RwF rule matching on this request.
         */
        rwf_prepare_forbidden_response(
            r,
            RWF_CACHE_BLOCK_RESPONSE
        );

        /*
         * Keep the normal error log light as well: one NOTICE for the first
         * cached follow-up, then individual cache hits are DEBUG-only.
         */
        if (cache_hit_count == 1) {
            ap_log_rerror(
                APLOG_MARK,
                APLOG_NOTICE,
                0,
                r,
                "mod_rwf: parallel-block "
                "client=%s host=%s uri=%s remaining=%" APR_TIME_T_FMT "s "
                "connection=%s accesslog=%s action=forbidden-fast",
                client_ip != NULL ? client_ip : "-",
                hostname,
                path,
                apr_time_sec(cache_remaining),
                conf->drop_connection == 1 ? "abort" : "keep",
                conf->suppress_blocked_accesslog == 1 ? "suppress-cache-hits" : "normal"
            );
        }
        else if (APLOGrdebug(r)) {
            ap_log_rerror(
                APLOG_MARK,
                APLOG_DEBUG,
                0,
                r,
                "mod_rwf: cache-hit "
                "client=%s host=%s method=%s uri=%s hit=%u remaining=%" APR_TIME_T_FMT "s "
                "hook=post_read_request action=forbidden-fast",
                client_ip != NULL ? client_ip : "-",
                hostname,
                method,
                path,
                cache_hit_count,
                apr_time_sec(cache_remaining)
            );
        }

        rwf_timing_finish(
            r,
            timing_ctx,
            client_ip,
            "cache-hit-block"
        );

        return HTTP_FORBIDDEN;
    }

    /*
     * Only cache misses reach the configured rules.
     */
    if (conf->rules == NULL || conf->rules->nelts == 0) {
        rwf_timing_finish(
            r,
            timing_ctx,
            client_ip,
            "no-rules"
        );

        return DECLINED;
    }

    path = (r->uri != NULL) ? r->uri : "";
    target = rwf_normalized_target(r, path);

    rules = (const rwf_rule *) conf->rules->elts;

    matched_rule = NULL;

    for (i = 0; i < conf->rules->nelts; ++i) {

        if (rwf_rule_matches(&rules[i], path, target)) {

            matched_rule = &rules[i];
            break;
        }
    }

    if (matched_rule == NULL) {
        rwf_timing_finish(
            r,
            timing_ctx,
            client_ip,
            "no-match"
        );

        return DECLINED;
    }

    hostname =
        (r->hostname != NULL)
        ? r->hostname
        : "-";

    method =
        (r->method != NULL)
        ? r->method
        : "-";


    /*
     * Save information in request notes.
     */
    apr_table_setn(
        r->notes,
        "rwf.match",
        matched_rule->name
    );

    apr_table_setn(
        r->notes,
        "rwf.policy",
        matched_rule->policy
    );


    /*
     * Remember the IP BEFORE producing the first blocked response.
     */
    cache_added = rwf_cache_add(client_ip);

    if (cache_added) {
        apr_table_setn(
            r->notes,
            "rwf.cache",
            "add"
        );

        ap_log_rerror(
            APLOG_MARK,
            APLOG_WARNING,
            0,
            r,
            "mod_rwf: cache-add "
            "client=%s "
            "ttl=%ds "
            "rule=%s",
            client_ip != NULL ? client_ip : "-",
            RWF_CACHE_TTL_SECONDS,
            matched_rule->name
        );
    }

    if (conf->drop_connection == 1) {
        /*
         * Preserve the first module-owned 403, but tell Apache that this
         * connection must not be reused. A cached parallel/follow-up request
         * will escalate this to an abort.
         */
        rwf_drop_client_connection(r, 0);
    }


    /*
     * Notify the local helper asynchronously.
     *
     * Whitelisted requests never arrive here.
     */
    (void) rwf_notify_helper(
        r,
        conf,
        client_ip,
        hostname,
        method,
        path,
        matched_rule
    );


    /*
     * The first matching request receives RwF's explanatory page.
     */
    rwf_prepare_forbidden_response(
        r,
        RWF_BLOCK_RESPONSE
    );


    ap_log_rerror(
        APLOG_MARK,
        APLOG_WARNING,
        0,
        r,
        "mod_rwf: match "
        "client=%s "
        "host=%s "
        "method=%s "
        "uri=%s "
        "rule=%s "
        "type=%s "
        "policy=%s "
        "connection=%s "
        "hook=post_read_request "
        "action=forbidden",
        client_ip != NULL ? client_ip : "-",
        hostname,
        method,
        path,
        matched_rule->name,
        rwf_rule_type_name(matched_rule->type),
        matched_rule->policy,
        conf->drop_connection == 1 ? "close" : "keep"
    );

    rwf_timing_finish(
        r,
        timing_ctx,
        client_ip,
        "rule-match-block"
    );

    return HTTP_FORBIDDEN;
}



/*
 * Register RwF immediately after Apache has read and parsed
 * the original client request.
 */
static void rwf_register_hooks(apr_pool_t *pool)
{
    (void) pool;

    ap_hook_post_config(
        rwf_post_config,
        NULL,
        NULL,
        APR_HOOK_MIDDLE
    );

    ap_hook_child_init(
        rwf_child_init,
        NULL,
        NULL,
        APR_HOOK_MIDDLE
    );

    ap_hook_post_read_request(
        rwf_post_read_request,
        NULL,
        NULL,
        APR_HOOK_FIRST
    );

    ap_hook_log_transaction(
        rwf_log_transaction,
        NULL,
        NULL,
        APR_HOOK_LAST
    );
}


/*
 * Apache module descriptor.
 */
module AP_MODULE_DECLARE_DATA rwf_module = {
    STANDARD20_MODULE_STUFF,
    NULL,                       /* create per-directory config */
    NULL,                       /* merge per-directory config  */
    rwf_create_server_conf,     /* create per-server config    */
    rwf_merge_server_conf,      /* merge per-server config     */
    rwf_directives,             /* configuration directives    */
    rwf_register_hooks          /* register hooks              */
};