# Copyright (C) 2026 Daniele Stefano Continenza <daniele@dascos.info>
# SPDX-License-Identifier: AGPL-3.0-or-later

name: syntax
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install nftables
        run: sudo apt-get update && sudo apt-get install -y nftables
      - name: Syntax
        run: ./tests/check-syntax.sh
      - name: Self test
        run: ./tests/self-test.sh
